# Generated by Django 3.1.2 on 2021-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_auto_20210729_1825'),
        ('user', '0002_auto_20210729_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='user', to='permission.Role', verbose_name='角色'),
        ),
    ]
