# Generated by Django 3.1.2 on 2021-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields',
            old_name='table_classify',
            new_name='classify',
        ),
    ]
