# Generated by Django 3.1.2 on 2021-06-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210627_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetbind',
            old_name='ClassifyBind',
            new_name='classify_bind',
        ),
    ]
