# Generated by Django 3.1.2 on 2021-06-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210627_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='table_classify',
            new_name='classify',
        ),
    ]
