# Generated by Django 3.1.2 on 2021-07-29 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodejointag',
            name='value',
            field=models.JSONField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='nodelinkoperapermission',
            name='read_member',
            field=models.ManyToManyField(blank=True, related_name='read_member', to=settings.AUTH_USER_MODEL, verbose_name='read 成员'),
        ),
        migrations.AlterField(
            model_name='nodelinkoperapermission',
            name='write_member',
            field=models.ManyToManyField(blank=True, related_name='write_member', to=settings.AUTH_USER_MODEL, verbose_name='write 成员'),
        ),
    ]
