# Generated by Django 3.1.2 on 2021-08-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_tree', '0002_auto_20210729_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeLinkServer',
        ),
    ]
