# Generated by Django 3.1.2 on 2021-08-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210627_1713'),
        ('service_tree', '0004_nodelinkclassify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelinkclassify',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_tree.servicetree', verbose_name='节点'),
        ),
        migrations.AlterUniqueTogether(
            name='nodelinkclassify',
            unique_together={('node', 'classify')},
        ),
    ]
