# Generated by Django 3.1.2 on 2021-08-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210627_1713'),
        ('service_tree', '0006_nodelinkasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodelinkasset',
            name='asset',
        ),
        migrations.AddField(
            model_name='nodelinkasset',
            name='asset',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link_asset', to='cmdb.asset'),
            preserve_default=False,
        ),
    ]
