# Generated by Django 3.1.2 on 2021-08-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_tree', '0007_auto_20210822_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodelinkasset',
            old_name='node',
            new_name='node_link',
        ),
    ]
