# Generated by Django 3.1.2 on 2021-08-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210627_1713'),
        ('service_tree', '0008_auto_20210822_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodelinkasset',
            unique_together={('node_link', 'asset')},
        ),
    ]
