# Generated by Django 3.1.2 on 2021-07-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='prem_menu',
        ),
        migrations.AlterModelTable(
            name='role',
            table='prem_role',
        ),
        migrations.AlterModelTable(
            name='rule',
            table='prem_rules',
        ),
        migrations.AlterModelTable(
            name='ruleclassify',
            table='prem_rule_classify',
        ),
    ]
