# Generated by Django 3.1.2 on 2021-07-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_auto_20210729_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='permission.menu', verbose_name='父节点'),
            preserve_default=False,
        ),
    ]
