# Generated by Django 3.1.2 on 2021-07-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20210729_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission.menu', verbose_name='父节点'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='role',
            field=models.ManyToManyField(blank=True, to='permission.Role', verbose_name='权限角色'),
        ),
    ]
