# Generated by Django 3.1.2 on 2021-08-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_auto_20210805_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rule_classify',
        ),
        migrations.AddField(
            model_name='rule',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission.rule'),
        ),
        migrations.DeleteModel(
            name='RuleClassify',
        ),
    ]
