# Generated by Django 3.1.2 on 2021-08-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_auto_20210805_1907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together=set(),
        ),
    ]
